services:
  - type: web
    name: ai-agent-router
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
          - key: OPENAI_API_KEY
            sync: false  # You will set this manually on Render