services:
  - type: web
    name: ai-agent-router
    env: python
    rootDir: web-server
    buildCommand: "pip install -r requirements.txt"
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # You will set this manually on Render

    # Frontend - Admin SPA
  - type: web
    name: admin-dashboard
    env: static
    rootDir: admin-dashboard
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html